[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/HTML/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/HTML/about.html"
  status = 200

[[redirects]]
  from = "/work"
  to = "/HTML/work.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/HTML/contact.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/HTML/index.html"
  status = 404 