[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[[redirects]]
  from = "/success"
  to = "/HTML/success.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/HTML/index.html"
  status = 200

[build.environment]
  NETLIFY_USE_YARN = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 